### ISSUE TITLE
news/ 301

### ISSUE THREAD

**Issue by CarlFK** [timvideos/website#12]
https://code.timvideos.us/news/

 <iframe width="100%" height="99%" frameborder="0" src="https://planet.timvideos.us/iframe"></iframe>

carl@twist:~$ curl https://planet.timvideos.us/iframe
<head><title>301 Moved Permanently</title></head>

**Comment by mithro** [comment]
The real problem is;
> Mixed Content: The page at 'https://code.timvideos.us/news/' was loaded over HTTPS, but requested an insecure resource 'http://planet.timvideos.us/iframe/'. This request has been blocked; the content must be served over HTTPS.

**Comment by mithro** [comment]
If you do a "curl -L https://planet.timvideos.us/iframe" it works fine...

**Comment by mithro** [comment]
I've fixed the empty frame on the website. However the news page isn't really all that useful at the moment.
